### ISSUE TITLE
Need a more user-friendly error for branches that don't cover all options

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#14]
This code *should* generate an error (and it does, see #8 ), but the error it generates is pretty cryptic:

```r
inside(M, { some_var = branch(parameter,
  "option1" ~ 1,
  "option2" ~ 2)
})

inside(M, { some_other_var = branch(parameter,
  "option1" ~ 3)
})
```

```
 Error in extract2(., assigned_parameter_option_value) : 
  attempt to select less than one element in get1index 
```

It would be better for this to generate something nice telling the user what option values they are missing in the second branch or something.

**Comment by abhsarma** [comment]
I am not sure how to address this when options are not named.

```r
inside(M, { some_var = branch(parameter, 1, 2) })

inside(M, { some_other_var = branch(parameter, 3, 4) })
```

Should this also throw an error? if not, then the current approach that we are using is not great to identify what a user is intending. I am not sure for unnamed branches, any approach would be appropriate, so I guess we can expand the documentation to say that if a user wants to reuse parameters, then they have to name branches?

**Comment by mjskay** [comment]
Yeah that would give an error. I don't think you need to limit branch re-use to named parameters though. This should work fine for example:

```r
inside(M, { some_var = branch(parameter, 1, 2) })

inside(M, { some_other_var = branch(parameter, 1, 2) })
```

Basically whatever names are generated from the spec should match the existing names if the parameter already exists?

**Comment by abhsarma** [comment]
right, but if you remember the example in #8 
if we want this to work:
```r
inside(M, { some_var = branch(parameter, option1 ~ 1, option2 ~ 2) })

inside(M, { some_other_var = branch(parameter, option1 ~ 3, option2 ~ 4) })
```

then this should also work, no?
```r
inside(M, { some_var = branch(parameter, 1, 2) })

inside(M, { some_other_var = branch(parameter, 3, 4) })
```

**Comment by mjskay** [comment]
I don't think the first implies the second should work. The names in the second example are different, whereas the names in the first example are the same. So the principle that a parameter can only be reused if all of the same options (by name) are provided is violated in the second example but not in the first example.

**Comment by abhsarma** [comment]
right, so basically parameters can be reused only if they have option names. Otherwise you can just do `some_other_var = some_var`. I think this constraint makes the expectations much clearer?

**Comment by mjskay** [comment]
Er, but the point I'm making is that options without explicit names still have names, they're just implicit. So you match on all the names, whether explicit or implicit, to decide if reuse of the parameter is valid.

**Comment by abhsarma** [comment]
I suspect this should also throw an error?

```r
inside(M, { 
  some_var = branch(parameter, "option1" ~ 1, "option2" ~ 2)
  some_other_var = branch(parameter, "option3" ~ 3, "option2" ~ 4)
})
```

**Comment by abhsarma** [comment]
^ this is throwing an error, but the error message is not meaningful. But to solve that, I'll need to implement some checks in other functions

**Comment by mjskay** [comment]
I'd suggest trying to think of a way to implement it that does not have many corner cases. Things having (lots of) corner cases is often a sign you haven't hit upon a good general rule for solving the problem.

In this case I think if you have a notion of a canonical name for any given option spec (whether given an explicit name or not) you could write the check in terms of those names and you wouldn't have corner cases.

**Comment by abhsarma** [comment]
No, I meant its difficult to account for the flexibility of declaring the multiverse. If parameter is reused and option names are not same, and the code is declared within a single `inside()` call vs two separate `inside()` calls, the errors would be at different points in the `parse_multiverse()` function
