### ISSUE TITLE
Do we need a notion of named chunks / the ability to replace specific chunks?

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#31]
This is related somewhat to #6 --- it might be nice for interactivity to be able to treat the multiverse code as a sequence of (indexable) code chunks rather just as a monolithic code block, and to be able to modify them. Could also help with #24.

**Comment by abhsarma** [comment]
This has been addressed. However, #6 has still not been completely addressed. Currently, it is executing code blocks in RMarkdown, but not when we try to knit the document, and figures are not shown.
