### ISSUE TITLE
Decide on %when% syntax

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#32]
I think it would be good to get feedback from others on this, but it feels a bit clunky currently.

The more I think about it, the more I am leaning towards overriding `if` for this. I think it would be fairly natural, and it would mean that you wouldn't need different syntax for the named versus unnamed case. E.g. these are valid currently:

```r
branch(param2,
  "d" ~ x + 1,
  "e" ~ x * 2,
  "f" %when% (param1 == "a") ~ x + 3,
  "g" ~ (x + 7) %when% (param1 == "a"),
  (x + 10) %when% (param1 == "a")
)
```

But could instead be:

```r
branch(param2,
  "d" ~ x + 1,
  "e" ~ x * 2,
  if (param1 == "a") "f" ~ x + 3,
  if (param1 == "a") "g" ~ x + 7,
  if (param1 == "a") x + 10
)
```

Which I think is clearer and also lets us drop a bunch of parens.

**Comment by abhsarma** [comment]
I hadn't actually closed this issue, got the number wrong in the commit message.
But one thing I noticed is that RStudio starts highlighting the lines starting with `if` because it things there's some kind of syntax error --- I feel this approach would get really annoying if that happens

**Comment by mjskay** [comment]
Huh that's interesting, and annoying. Looks like a bug in RStudio's syntax parser when an if statement with a double-sided formula as the right-hand side is used as a function argument. I'd file an issue with them?

This gives a syntax error:

```r
quote(
  if (TRUE) a ~ b
)
```

While these don't:

```r
if (TRUE) a ~ b

quote(
  if (TRUE) ~ b
)

quote(
  if (TRUE) a
)
```

Even though all are valid.

If you don't want to file an issue I can.

**Comment by abhsarma** [comment]
gotcha. I can file it, but I feel like you might be able to describe it better?

**Comment by mjskay** [comment]
Sure, reported here: https://github.com/rstudio/rstudio/issues/7270

**Comment by abhsarma** [comment]
Thanks, in that case, should we remove this issue from the milestone until rstudio fixes this bug?

**Comment by mjskay** [comment]
Hmmmmmm good question. I do really like the if syntax but I guess we can wait to change it when it doesn't raise spurious syntax errors in rstudio

**Comment by abhsarma** [comment]
I'll implement in in a separate branch and leave it there. We can merge it with the master branch whenever the bug gets fixed.

**Comment by mjskay** [comment]
good idea!

**Comment by abhsarma** [comment]
so do we deprecate the `%when%` thing?

**Comment by mjskay** [comment]
Up to you... Could leave it in as an alternate syntax until the if thing works, then deprecate? Unless there's another way to do conditions already

**Comment by abhsarma** [comment]
there's also the `branch_assert` function which is like a post-hoc correction of the multiverse

**Comment by mjskay** [comment]
ah right. that feels more awkward though. I'd say it wouldn't hurt to leave %when% in for now and change it later. The package is still in the early stages so some API instability is to be expected.
