### ISSUE TITLE
variables named `df` in the globalenv() cannot be used/executed in the multiverse?

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#41]
This is currently throwing an error:

```r
M = multiverse()
df <- data.frame(x = 1:10) %>% mutate( y = x^2 + sample(10:20, 10))
M$df <- ~ df %>%
      mutate( z = branch( value_y, 
                          "none" ~ y,
                          "log" ~ log(y)
                        ))
```

This throws an error as well:
```r
M = multiverse()
df <- data.frame(x = 1:10) %>% mutate( y = x^2 + sample(10:20, 10))
M$df.s <- ~ df %>%
      mutate( z = branch( value_y, 
                          "none" ~ y,
                          "log" ~ log(y)
                        ))
```

However, **this does not** throw an error:
```r
M = multiverse()
data.raw <- data.frame(x = 1:10) %>% mutate( y = x^2 + sample(10:20, 10))
M$df <- ~ data.raw %>%
      mutate( z = branch( value_y, 
                          "none" ~ y,
                          "log" ~ log(y)
                        ))
```

**Comment by abhsarma** [comment]
@mjskay I think this is assigning the stats function `df` here?

If so, solving #18 should address this as well?

**Comment by mjskay** [comment]
Yeah if I replace the initial `.results` environments in the multiverse table with the global environment it seems to work. So I would say those environments probably need to be adjusted to be child environments of the environment that first calls `multiverse()`

**Comment by abhsarma** [comment]
I am not able to replicate this error currently, so I assume that we'd solved this at some point

**Comment by mjskay** [comment]
Have you added a test for it? If not it would be a good idea so it doesn't come back

**Comment by abhsarma** [comment]
Sounds good
