### ISSUE TITLE
can we use the tree structure of the multiverse to share some computation across universes?

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#47]

**Comment by abhsarma** [comment]
In implementing this, did we ever decide on what to do with the following problem?

Say the code is written like this (in a multiverse code block:

```r
df <- df %>%
		mutate( 
                              x = branch(...),
                              a = branch(...)
                 ) %>%
		mutate( y = ... )

df <- df %>%
                filter( z = branch(...) )	
```

this can easily be broken down into a list of code statements and the first can be put at a higher level than the second in the tree structure.

However, the same can also be written like this, and parsing would be much more complicated:

```r
df <- df %>%
		mutate( 
                              x = branch(...),
                              a = branch(...)
                 ) %>%
		mutate( y = ... ) %>%
                 filter( z = branch(...) )	
```

I remember discussing this, but not sure what we decided to do for the actual implementation. Should we leave ti to the user describing good practice and optimisation --- using lots of pipes with multiple parameters would slow down the multiverse execution?

**Comment by mjskay** [comment]
Yeah I think we don't optimize beyond the level of code chunks they provide to us, at least for now.

**Comment by abhsarma** [comment]
```r
inside(M, {
    df <- df %>%
        mutate( x = branch(...) ) # 2 options
})

inside(M, {
    df <- df %>%
        mutate( y = ... ) %>%
        mutate( z = branch(...) ) # 3 options
})
```
Steps:

- [ x ] break the code into relevant sub-expressions which correspond to each successive step in the execution (in the above example this would be 5 different expressions)
- [ x ] create environments as child environments of expressions with branches that are declared previously (here we would create 3 + 3 x 2 environments, with the 6 latter environments being a child of the 3 initial environments)
- [ ] evaluate the code in the corresponding environment
- [ ] create a data-structure to store this execution plan

I don't think this is too difficult to implement as discussed rn. However, I am not sure about (4) data structure. I feel like this could potentially be at odds with the multiverse data structure that we have been using so far.

**Comment by mjskay** [comment]
Oh, I was assuming the above would be two expressions (one for each inside statement). If you break things up further than that I would assume you would break it up at the lowest level at the statement level, and not try to tear apart pipes or other function calls (that seems messy?).

**Comment by abhsarma** [comment]
Yeah, it would be two expressions initially, but once you parse the branches (which have 3 and 2 options), you would get 5 different expressions?

**Comment by mjskay** [comment]
Ah my bad, I misunderstood. Yeah that makes sense.

Re: point 4, my first thought was you could create a tree (probably using {igraph} or something), but then I realized you don't need the tree you just need the breadth-first order of nodes in the tree, which happens to just be all the expressions in the same order as they appear in the code blocks. So one option would be to have a list with a parallel structure to the list of code blocks where each element is a list of expressions.

Worth thinking about: at some point scalability might be an issue with these lists (and the multiverse table too)
