### ISSUE TITLE
Decide on the use / deprecation of `$`

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#55]
We've stopped using the `$`<- for variable assignment in the multiverse.
However, we still support using `$` for accessing / retrieving variables from the multiverse.

Decide whether this is consistent with the new API or should be deprecated.

**Comment by mjskay** [comment]
My gut is this eventually gets dropped in favor of having people explicitly pull things from the correct environment, but I could be wrong

**Comment by abhsarma** [comment]
I am leaving the `$` to access objects from the multiverse for now, but disabling the use of assignment: `$<-` 

Can revisit this later.

**Comment by abhsarma** [comment]
- [ ] throw error on assignment
