### ISSUE TITLE
Deal with VignetteBuilder NOTE

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#59]
From github action checks:

> Package has a VignetteBuilder field but no prebuilt vignette index.

Presumably this is because you have --no-build-vignettes on, which is understandable since building them takes forever :).

One solution would be to use the approach in tidybayes, which (when the test environment is CRAN) "builds" them into HTML but doesn't execute any of the code chunks. @abhsarma let me know if you want me to set that up.

For reference, how long does it take to build the vignettes currently? I started a build but killed it after 5 minutes because I didn't feel like waiting.

**Comment by mjskay** [comment]
(since it is just a note we could also leave it as-is for now, as notes won't cause the github action check to fail, only warnings)

**Comment by abhsarma** [comment]
I think it takes around 20 mins or so but its mostly one of the vignettes (the DANCE example from the EMAR paper) I'll take a look at it and see if that one can be sped up somehow

**Comment by abhsarma** [comment]
Unless I am missing something, I don't seem to be getting this note anymore (on the commits to the dev branch). Should we close this?

**Comment by mjskay** [comment]
I still see the note on github actions? The runs don't fail on NOTEs so you have to go in and read the Check output every once in awhile

**Comment by abhsarma** [comment]
ah yes, couldn't find it. I am not sure how to deal with this and couldn't find anything helpful online either. Would you mind taking a look at it whenever you get a chance?

**Comment by mjskay** [comment]
K I can look at that. what's the timeline for this?

**Comment by abhsarma** [comment]
whenever you get the chance I guess. I think besides this, we can decide on whether we want the tangle interaction working before we do a beta release

**Comment by mjskay** [comment]
ah yeah. the tangle stuff would be cool, since that kind of differentiates it from other stuff

**Comment by abhsarma** [comment]
Right, but between the work that needs to be done on the vis, parallelisation stuff and tangle, I am a little stretched and not sure when I'll be able to get at that. I am just worried that of pushing back releasing it out there too much? Maybe it might be useful to talk about prioritising things?

**Comment by abhsarma** [comment]
okay this is because all the checks on github actions do not build vignettes, so it goes away if I just run `devtools::check(remotes = TRUE, manual = TRUE)` or `devtools::check_win_devel()`
