### ISSUE TITLE
Create custom code chunk type for rmarkdown in rstudio

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#6]
After #2 is done, we can look into creating a custom code chunk type for markdown. Perhaps something like this:

<pre>
```{multidy optional_chunk_name, multiverse = M}
df = some_code_to_create_df()
df
```
</pre>

Which would be compiled into something like this:

<pre>
```{r optional_chunk_name}
inside(M, {
  df = some_code_to_create_df()
  df
})
```
</pre>

Then we could even create an addin + keyboard shortcut for RStudio to create these code chunks (much like there is a keyboard shortcut for creating R code chunks). Would want to make sure that autocomplete still works for these.

**Comment by abhsarma** [comment]
- [ ] create a custom code chunk type `multidy`

- [ ] read code from `multidy` and execute it using inside

- [ ] Get multiverse object from options$multiverse (which gives a character) #18 

- [ ] add keyboard shortcut

**Comment by abhsarma** [comment]
Not sure how to write unit tests for this. Any suggestions?

**Comment by mjskay** [comment]
Ah, hrm. Dunno. There might be some ways of doing it by calling knitr functions directly? You could look at how the rmarkdown package does it?

**Comment by mjskay** [comment]
Also, if you haven't already, this might be a case where seeing if it is even possible first is a good idea before writing tests... I have a feeling doing this in a seemless way inside rstudio might actually be hard or even impossible currently (at least, having the custom code chunk type work like r code with autocomplete and all that). Unless you've already figured that out?

**Comment by abhsarma** [comment]
Not sure I get the autocomplete part --- what do you mean?

**Comment by mjskay** [comment]
like, having rstudio actually treat the code chunk as if it is an R code chunk when you are editing the code, so that it does nice things like lets you use autocomplete, does syntax highlighting, and formats outputted tables as interactive widgets and the like.

**Comment by abhsarma** [comment]
I am not sure about the formatting of tables, but it does still autocomplete, and highlights the syntax by default

**Comment by mjskay** [comment]
huh cool. can you get it to run R code inside Rstudio if you write a bare-bones chunk type that's called "multidy" ?

**Comment by abhsarma** [comment]
Yeah. I think I committed this to the dev branch. It's in the Rmd file

**Comment by mjskay** [comment]
I get this error trying to load the multidy package on `dev`:

```
Loading multidy
Error in eval(exprs[i], envir) (from eng_multidy.R#1) : object 'knit_engines' not found
```

**Comment by mjskay** [comment]
if I load knitr it works but it doesn't display the output of the code chunk, it displays a number?

e.g. I would expect this to output the data frame from the current universe:

<pre>
```{multidy, multiverse = M}
df
```
</pre>

but it outputs this:

```
101
```

**Comment by mjskay** [comment]
I also get weird issues with multiline code chunks:

<pre>
```{multidy, multiverse = M}
x = 5
x + 1
```
</pre>

```
Error in parse(text = x) : <text>:1:6: unexpected symbol
1: x = 5x
         ^
```
