### ISSUE TITLE
Unorthodox order of suggests / imports 

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#61]
Any particular reason Suggests are listed above Imports in DESCRIPTION? In most other packages they are listed the other way around (which also matches the order they are shown on CRAN). I don't think it makes a difference except for the potential to create errors due to the unconventional order (I just accidentally put some imports under Suggests when I meant to put them under Imports :) ).

@abhsarma If you don't object I'm going to put them into the more conventional order.

**Comment by abhsarma** [comment]
Sure, go ahead. Its probably because I wasn't aware of the conventions, and never noticed the need to fix it

**Comment by mjskay** [comment]
Cool that's what I figured. Will fix.
