### ISSUE TITLE
Document .options parameter for branch()

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#64]
It does not seem to be documented?

**Comment by abhsarma** [comment]
do you mean the different options arguments that can be specified using `branch()` ?

**Comment by mjskay** [comment]
Yeah, if I look at `help("branch")` it does not list the `.options` argument.

**Comment by abhsarma** [comment]
rn its specified as `...` but I guess I can expand on it and have a section called **Options**
However, I dont think it should be a `.options` argument as that might give the perception that its a single argument whereas the way it is specified actually seems like you can declare multiple
What do you think?

**Comment by mjskay** [comment]
I'm referring to the `.options` argument that we created in https://github.com/MUCollective/multiverse/issues/36#issuecomment-539303694 and which is a separate alternative to `...`. Since it's not the same as `...` it should be documented as a separate parameter, no?

**Comment by abhsarma** [comment]
oh sorry, I forgot about that one!

**Comment by mjskay** [comment]
No worries! 🙂

**Comment by abhsarma** [comment]
also one thing I realised is that R usually does partial matching with its functions, but since branch is not a function, it wont support partial matching on args like `.options`. something we should be concerned about?

**Comment by mjskay** [comment]
Nah, partial matching is a horrible misfeature
