### ISSUE TITLE
Name of `multiverse_table()` function

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#65]
The name `multiverse_table()` feels a little awkward. It is in some middle ground of either too general or too specific.

I could imagine going in a standardized direction, and implementing versions of `as.data.frame()` and/or `as_tibble()`. 

Or I could imagine a more specific direction, e.g. coming up with a good name for the type of table, or some kind of verb word for the translation to table.

**Comment by abhsarma** [comment]
should we also create a class for the output of this? since we have a wrapper function now which works on the output of this function, it might be useful to assign it a class?

**Comment by mjskay** [comment]
Depends. I never did do this with tidybayes on the assumption that the function is useful on standard data frames as long as they conform to the required format, and kind of prefer that lightweight approach unless you are doing something where it is really needed. I would probably hold off on adding a class unless/until some benefit of doing so is apparent - is there one now?

**Comment by abhsarma** [comment]
I was just thinking of checking the input data frame. If accidentally someone passes in the multiverse object or some random data frame, then the error would be quite cryptic?

**Comment by mjskay** [comment]
You could make a generic function that either takes data frames or multiverse objects, then if its a data frame you could have a check for the .results column? My concern with requiring a particular class for the data frame is that you have to be sure that any other function someone uses on the data frame preserves other classes.

**Comment by abhsarma** [comment]
yeah that makes sense. the resultant data frame should be easily compatible with other functions so leaving as data frame makes sense. Thanks I'll make changes to #63

**Comment by abhsarma** [comment]
re: something generic could be `as_table()` or `as_tibble()`
Can't seem to think of something specific, but the table is in fact a tidy df of the different parameter combinations and the corresponding results? so something along those lines?

**Comment by mjskay** [comment]
Could use the existing S3 generic `tibble::as_tibble()`.

I suppose you could also provide an implementation of the existing generic `as.data.frame()` for people who don't want tidyverse things, dunno

**Comment by abhsarma** [comment]
- [ ] use `expand` to retrieve multiverse table
