### ISSUE TITLE
Remove code which throws error from the multiverse

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#67]
M <- multiverse()

inside(M, { some_var = branch(parameter,
  "option1" ~ 1,
  "option2" ~ 2)
})

inside(M, { some_other_var = branch(parameter,
  "option3" ~ 3,
  "option2" ~ 4
)
})

this throws an error, as it should ( see #14 ), but if the user then goes and corrects it, then it would still throw an error because the code is `some_other_var = branch(parameter,   "option3" ~ 3,  "option2" ~ 4)` is in the multiverse. This should be removed.

**Comment by abhsarma** [comment]
Now code is only added after `parse_multiverse` executes. This makes sure that every universe has a valid R code. If the execution of the entire multiverse throws errors in certain universes, that might be more difficult to solve

**Comment by mjskay** [comment]
That is a good point re: errors during execution. Do we have a way to handle that currently? Probably should capture errors during runs somehow rather than having a single universe kill everything

**Comment by abhsarma** [comment]
Could put everything inside a try block or something of that sort. If there's an error, then we can show messages to the user.
