### ISSUE TITLE
Use unnamed label syntax for generated multiverse blocks?

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#69]
Why use the explicitly named parameter for generated block labels / in the docs? I didn't even know you could do this:

<pre>
```{multiverse label = default-m-2, inside = M}

```
</pre>

When this works equally well and is consistent with every other instance of named blocks in markdown I've seen:

<pre>
```{multiverse default-m-2, inside = M}

```
</pre>

I'd say it's better to go with what people tend to see / know from other contexts? (also is shorter, which is nice given the verbose names). Unless I'm crazy and people actually use the `label` parameter by name.

**Comment by abhsarma** [comment]
yeah, this can be easily implemented. Just requires some handling of the lists of different lengths. All of the info gets passed as `options$params.src` and if a label is not explicitly named, we get a list of three character vectors of different lengths. So basically need to handle the case where labels are and not are explicitly specified

**Comment by mjskay** [comment]
Oh I thought it already worked? I left the arg name off in my tests and it worked fine interactively anyway (didn't test knitting)

**Comment by abhsarma** [comment]
It was throwing errors while knitting, and looking at the (now old) code I can't imagine it working without these changes

**Comment by mjskay** [comment]
Ha 🙂
