### ISSUE TITLE
setup block in rmarkdown vignettes

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#70]
the setup blocks in the vignettes currently look like this:

<pre>
```{r, setup, include=FALSE}
library(knitr)
opts_knit$set(
  echo = TRUE,
  fig.width = 6, 
  fig.height = 4,
  output.dir="vignettes"
)
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(broom)
library(gganimate)
library(cowplot)
library(stringr)
library(forcats)
library(multiverse)
```
</pre>

Is there a reason for manually setting the output directory? I haven't seen that before in vignettes and I suspect that will cause some things to break (like pkgdown if we want pkgdown docs). Removing it should cause no problems.

For readers' sake, I find it is also good to make the block that loads libraries visible so that they can know what packages are needed for a vignette (not everyone looks at the source of vignettes, often people are looking only at the compiled versions on a website). So I would do something like this:

<pre>
```{r, chunk_setup, include=FALSE}
opts_knit$set(
  echo = TRUE,
  fig.width = 6, 
  fig.height = 4
)
```

```{r setup, message = FALSE, warning = FALSE}
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(broom)
library(gganimate)
library(cowplot)
library(stringr)
library(forcats)
library(multiverse)
```
</pre>

The message = FALSE and warning = FALSE allow the libraries to be listed but doesn't print package startup messages (which can be annoying)

**Comment by mjskay** [comment]
PS happy to make this change if you want me to

**Comment by abhsarma** [comment]
re: the explicit naming of package directory, I think I was trying to store the knitted documents and I forgot to take it out. I'll make a commit removing that and cleaning up the setup and setting blocks
