### ISSUE TITLE
Allow a branch to be used multiple times as long as the options are the same

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#8]
- [x] This should be valid:

```r
M$some_var = ~ branch(parameter,
  "option1" ~ some expr 1,
  "option2" ~ some expr 2
)

M$some_other_var = ~ branch(parameter,
  "option2" ~ some expr 3,
  "option1" ~ some expr 4
)
```

because the option names are the same (and should work **even if they are out of order**). 

- [x] This should throw an error:

```r
M$some_var = ~ branch(parameter,
  "option1" ~ some expr,
  "option2" ~ some expr
)

M$some_other_var = ~ branch(parameter,
  "option1" ~ some expr
)
```

Because option2 is not accounted for in the second branch. **Add a test for this**.

One solution is to just take the union of all the option names when merging, and then have the error happen during execution of universes that are impossible

**Comment by abhsarma** [comment]
Right now, what this does is:
```r
inside(M, {some_var = ~ branch(parameter,
  "option1" ~ some expr 1,
  "option2" ~ some expr 2
)
})

inside(M, {some_other_var = ~ branch(parameter,
  "option2" ~ some expr 3,
  "option1" ~ some expr 4
)})
```

creates 4 unique universes, with parameters being `parameter` and `parameter.1` with 2 options for each. I am not sure if that's the desired behavior. Also affects #14.

**Comment by mjskay** [comment]
Ah yeah, that's not the desired behavior. It should only create two universes?

**Comment by abhsarma** [comment]
I'll take a look, but might need a more customised implementation than the one we have right now
