### ISSUE TITLE
problem with conditions

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#81]
There seems to be some error with conditions due to the new implementation, where all the branches are getting executed. Need to identify all the paths which are incompatible with each other and fix this problem.

Seems to happen when branches are declared after the branches with conditions

**Comment by mjskay** [comment]
add some tests for this when you fix it if you weren't going to already :)

**Comment by abhsarma** [comment]
yeah, I didn't realise it at the time, but the tests I had broke because the workflow in the backend changed completely. So need to rewrite those tests.

**Comment by mjskay** [comment]
Ah that's always frustrating, my sympathies
