### ISSUE TITLE
.error or .messages column for expand()

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#82]
Since it seems like expand() is going to be the primary interface for interacting with the multiverse, it might be useful to have a .error column to indicate which universe has thrown an error?

**Comment by mjskay** [comment]
This is related to #68, yes? I think the .error column should contain a traceback object of the error. I like the idea of having a .messages column as well to contain any messages (not sure how hard it is to intercept messages and also have them in the normal universe output).

**Comment by abhsarma** [comment]
I think traceback is a good idea, but the base `traceback` won't work with tryCatch which we are using so that errors in universes don't stop the multiverse execution.
Seems like there's `evaluate::try_capture_stack` worth a shot?

**Comment by mjskay** [comment]
ooo, good catch!
