### ISSUE TITLE
add print() function for multiverse objects

### ISSUE THREAD

**Issue by mjskay** [MUCollective/multiverse#9]
Something simple, like listing parameters and options or something like that

**Comment by abhsarma** [comment]
implement a custom `print` function
- [ ] summary of what the parameters and options are
- [ ] a structure version of it: list of all parameters and upto n option values, similar to the str function

**Comment by abhsarma** [comment]
Do you know of an example of this implementation? I am not quite sure how to go about this

**Comment by mjskay** [comment]
You should be able to just define a function `print.multiverse = function(x, ...)` for the s3 class (assuming that's called `multiverse`?)
